author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /osh-test-1
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://images.readux.ecds.emory.edu:8443/cantaloupe/iiif/2/osh-formal-go_OSH-cover1.jpg/full/full/0/default.jpg
image_size:
  page:
    height: 3916
    width: 3387
permalink: pretty
publication_info:
  date: '2019'
  editors: []
  title: 'Formal Eval: OSH Google (by word)'
show_annotation_author: true
source_info:
  title: 'Formal Eval: OSH Google (by word)'
  via_readux: true
tagline: an annotated digital edition
title: 'Formal Eval: OSH Google (by word)'
url: https://sarepal.github.io
version: 0.7
